-- InsertData - Bairros de Corumbá
INSERT INTO `PROD_Bairro` (`nome`, `ativo`, `updated_at`) VALUES
('Aeroporto', true, NOW()),
('Boa Esperança', true, NOW()),
('Bom Jesus', true, NOW()),
('Centro', true, NOW()),
('Cristo Redentor', true, NOW()),
('Dom Bosco', true, NOW()),
('Generoso', true, NOW()),
('Guaicurus', true, NOW()),
('Guató', true, NOW()),
('Maria Leite', true, NOW()),
('Nova Corumbá', true, NOW()),
('Nova Lima', true, NOW()),
('Novo Horizonte', true, NOW()),
('Nopulândia', true, NOW()),
('Padre Ernesto Sassida', true, NOW()),
('Popular Nova', true, NOW()),
('Popular Velha', true, NOW()),
('Primavera', true, NOW()),
('Progresso', true, NOW()),
('Santa Terezinha', true, NOW()),
('Universitário', true, NOW()),
('Vila Mamona', true, NOW()),
('Vila Real', true, NOW()),
('Vila Guarani', true, NOW());
